---
- name: Deploy Prometheus Monitoring Server
  hosts: monitoring
  become: yes
  vars:
    prometheus_version: "2.53.0"
    prometheus_port: 9090
    prometheus_scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['localhost:9100']
  roles:
    - prometheus