---
- name: Ensure dependencies are installed
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == "Debian"

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"  

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present
  notify: Restart Docker

- name: Ensure Docker service is enabled and running
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes

- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users | length > 0