---
- name: Stop Docker service
  service:
    name: "{{ docker_service }}"
    state: stopped
  ignore_errors: true
  tags: ['uninstall_docker']

- name: Disable Docker service
  service:
    name: "{{ docker_service }}"
    enabled: no
  ignore_errors: true
  tags: ['uninstall_docker']

- name: Remove Docker package
  package:
    name: "{{ docker_package }}"
    state: absent
  tags: ['uninstall_docker']

- name: Remove Docker repository (Debian)
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: absent
  when: ansible_os_family == "Debian"
  tags: ['uninstall_docker']

- name: Remove Docker GPG key (Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: absent
  when: ansible_os_family == "Debian"
  tags: ['uninstall_docker']

# Optional: remove leftover docker data (uncomment if desired)
# - name: Remove Docker data directory
#   file:
#     path: /var/lib/docker
#     state: absent
#   tags: ['uninstall_docker']