---
galaxy_info:
  author: Danteesh
  description: Install and configure Docker
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
  galaxy_tags:
    - docker
    - containers
dependencies: []
